login:
  username: fakeuser
  password: fakepass
  
sheets:  
  - name: non_existant_spreadsheet
    key: key_google_doc_key
    
output:
  yaml_path: 'data'
  migrations:
    path: 'migrations'
    models: 'models'
    
svn:
  bin: /usr/bin/svn
  repo: svn://repo/path
  
git:
  bin: /usr/local/bin/git
    
cron:
  project_base: /home/user/project
  version:
    file: /home/user/project/config/version
  options: -g -m -l -i
